name: Docker Build and Push
description: Build the Java microservice
inputs:
  run_number:
    required: true
    description: The GitHub Actions Workflow run number
  github_repo:
    description: 'The github repo'
    required: true
  github_token:
    description: 'The github token'
    required: true
  dockerhub_username:
    description: 'The dockerhub username'
    required: true
  dockerhub_password:
    description: 'The dockerhub password'
    required: true
  octopus_url:
    description: 'The octopus server'
    required: true
  octopus_apikey:
    description: 'The octopus apikey'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone code repo
      uses: actions/checkout@v2

    - name: Install Octopus CLI ðŸ™
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: 'latest'

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: 5.x

    - id: determine_version
      name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        additionalArguments: /overrideconfig mode=Mainline

    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: adopt
        cache: 'maven'

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '22.3.0'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - name: Checkstyle
      run: ./mvnw --batch-mode checkstyle:check
      shell: bash
      working-directory: java

    - name: Install modules
      run: ./mvnw --batch-mode install -DskipTests
      shell: bash
      working-directory: java

    - name: Test Backend
      run: ./mvnw --batch-mode test
      shell: bash
      working-directory: java/products-microservice

    - name: Test Shared Library
      run: ./mvnw --batch-mode test
      shell: bash
      working-directory: java/microservice-utils

    - name: Build with Maven
      run: ./mvnw --batch-mode package --file pom.xml -DskipTests
      shell: bash
      working-directory: java/products-microservice

    - name: Generate JaCoCo Badges
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/products-microservice/target/jacoco-report/jacoco.csv
        coverage-badge-filename: products-microservice.svg
        branches-badge-filename: products-microservice-branches.svg

    - name: Generate JaCoCo Badges for Shared Library
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/microservice-utils/target/site/jacoco/jacoco.csv
        coverage-badge-filename: microservice-utils.svg
        branches-badge-filename: microservice-utils-branches.svg

    - name: Update resources
      if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
      uses: test-room-7/action-update-file@v1.6.0
      with:
        file-path: |
          .github/badges/microservice-utils.svg
          .github/badges/microservice-utils-branches.svg
        commit-msg: Update badges
        github-token: ${{ inputs.github_token }}

    # This step generates a Source Bill of Materials (SBOM) package that captures all the dependencies compiled
    # into the application.
    - name: Generate SBOM
      run: ./mvnw cyclonedx:makeAggregateBom -DskipTests --no-transfer-progress --batch-mode
      shell: bash
      working-directory: java

    # We capture the SBOM, which is found in the file bom.xml, as a versioned ZIP package.
    - name: Build SBOM package
      env:
        OCTOPUS_URL: ${{ inputs.octopus_url }}
        OCTOPUS_API_KEY: ${{ inputs.octopus_apikey }}
      run: >
        octopus package zip create
        --id products-microservice-sbom
        --version ${{ steps.determine_version.outputs.semVer }}
        --include **/bom.xml
      shell: bash
      working-directory: java/products-microservice

    # The SBOM package is pushed to the Octopus built-in feed.
#    - name: Push SBOM Package
#      run: >
#        octo push
#        --package products-microservice-sbom.${{ steps.determine_version.outputs.semVer }}.zip
#        --server ${{ inputs.octopus_server }}
#        --apiKey ${{ inputs.octopus_apikey }}
#        --space "${{ inputs.octopus_space }}"
#        --overwrite-mode OverwriteExisting
#      shell: bash
#      working-directory: java/products-microservice

    # Integration tests are performed with Postman using an exported collection.
    - name: Build Postman package
      env:
        OCTOPUS_URL: ${{ inputs.octopus_url }}
        OCTOPUS_API_KEY: ${{ inputs.octopus_apikey }}
      run: >
        octopus package zip create
        --id products-microservice-postman
        --version ${{ steps.determine_version.outputs.semVer }}
        --include test.json
        --base-path postman-products
      shell: bash
      working-directory: java

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    # The Postman package is pushed to the Octopus built-in feed.
#    - name: Push Postman Package
#      run: >
#        octo push
#        --package products-microservice-postman.${{ steps.determine_version.outputs.semVer }}.zip
#        --server ${{ inputs.octopus_server }}
#        --apiKey ${{ inputs.octopus_apikey }}
#        --space "${{ inputs.octopus_space }}"
#        --overwrite-mode OverwriteExisting
#      shell: bash
#      working-directory: java

    # The Docker image used to run Postman tests is built and pushed.
    - name: Build, tag, and push postman image to Dockerhub
      if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
      run: |
        cd postman
        docker build -t octopussamples/postman .
        docker push octopussamples/postman
      shell: bash
      working-directory: java

    # The Docker image is built and pushed. It uses the same tag as the SBOM package version to allow us to match the
    # two packages in Octopus.
    - name: Build, tag, and push image to Dockerhub
      run: |
        docker build -f src/main/docker/Dockerfile.legacy-jar -t octopussamples/octopub_products:${{ steps.determine_version.outputs.semVer }} .
        docker push octopussamples/octopub_products:${{ steps.determine_version.outputs.semVer }}
      shell: bash
      working-directory: java/products-microservice

    - name: Build and deploy serverless package
      run: |
        # Need to compile in docker image to fix https://github.com/quarkusio/quarkus/issues/25897
        ./mvnw --batch-mode package -P "lambda,native" -DskipTests -Dquarkus.profile=faas -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
        zip products-service.${{ steps.determine_version.outputs.semVer }}.zip serverless.yaml target/function.zip
        mvn deploy:deploy-file \
          --batch-mode \
          -Dfile=products-service.${{ steps.determine_version.outputs.semVer }}.zip \
          -Durl="https://${{ github.actor }}:${{ inputs.github_token }}@maven.pkg.github.com/${{ github.repository }}" \
          -DgroupId=com.octopus \
          -DartifactId=products-service \
          -Dversion=${{ steps.determine_version.outputs.semVer }} \
          -Dpackaging=zip
      shell: bash
      working-directory: java/products-microservice

#    - name: Build and push lambda package
#      run: |
#        mv target/function.zip products-microservice-lambda.${{ steps.determine_version.outputs.semVer }}.zip
#        octo push \
#          --package products-microservice-lambda.${{ steps.determine_version.outputs.semVer }}.zip \
#          --server ${{ inputs.octopus_server }} \
#          --apiKey ${{ inputs.octopus_apikey }} \
#          --space "${{ inputs.octopus_space }}" \
#          --overwrite-mode OverwriteExisting
#      shell: bash
#      working-directory: java/products-microservice