-- Script generated by Redgate Compare v1.19.6.13291


-- deployment: Dropping product_aud.audio_id...
ALTER TABLE product_aud DROP COLUMN audio_id;


-- deployment: Dropping product.new_product...
ALTER TABLE product DROP COLUMN new_product;

