-- Script generated by Redgate Compare v1.19.7.13456


<<<<<<< HEAD
-- deployment: Dropping audiobooks...
DROP TABLE audiobooks;


-- deployment: Dropping auditors.Test...
ALTER TABLE auditors DROP COLUMN Test;
=======
-- deployment: Dropping metaversebookshop...
DROP TABLE metaversebookshop;
>>>>>>> 6078ca6e31bd4e551730d0052cfc449e7a0c3cda

