-- Script generated by Redgate Compare v1.19.7.13456


-- deployment: Creating audiobooks...
CREATE TABLE audiobooks (
    Author varchar(100) NULL,
    Book varchar(100) NULL,
    Price varchar(100) NULL
);


-- deployment: Creating auditors.Test...
ALTER TABLE auditors ADD COLUMN Test varchar(100) NULL;

