-- Script generated by Redgate Compare v1.19.7.13456


-- deployment: Creating addressbook...
CREATE TABLE addressbook (
    FirstName varchar(100) NULL,
    LastName varchar(100) NULL,
    StreetAddress varchar(100) NULL
);

