-- Script generated by Redgate Compare v1.19.7.13456


-- deployment: Creating vrbookstore...
CREATE TABLE vrbookstore (
    Author varchar(100) NULL,
    BookName varchar(100) NULL,
    Price varchar(100) NULL
);

