name: Build Self Contained Image
permissions:
  contents: write
  packages: write
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!.github/badges/*'
      - '!README.md'
      - '!python/**/*'
      - '!octopus/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Version Number
        id: version-generator
        run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push worker image to Dockerhub
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
        run: |
          docker build -f docker/selfcontained/Dockerfile -t octopussolutionsengineering/octopub:${{ steps.version-generator.outputs.version }} .
          docker push octopussolutionsengineering/octopub:${{ steps.version-generator.outputs.version }}
          docker tag  octopussolutionsengineering/octopub:${{ steps.version-generator.outputs.version }} octopussolutionsengineering/octopub:latest
          docker push octopussolutionsengineering/octopub:latest
        shell: bash

